name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: ['.github/**']
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by ${{ github.event_name }}"
          echo "The branch is ${{ github.ref }} in repository ${{ github.repository }}"

      - name: 'Checkout Repository...'
        uses: actions/checkout@v4

      - name: List files in repo
        run: |
          echo "Repository ${{ github.repository }} contains these files:"
          tree
    
